# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bbf04ecc7281920bff11b847e47f89fc510f5a8019d876167dab0dfd6fa5b7bb72213cb46fb2a19f915630e858402c65d22a6036114c50dbb06a4cda320be89

test:
  secret_key_base: 9bf4953ed5b44f8c9185d978cf64e468ce0818bca0b0b79f9d067d3fd89c5957951f2f859faf1143d860b37e74d68a6c7ee78ac241759992e1e315dc9a7e8e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
